---
abstract: 'Backwards compatibility wrapper for say()'
author:
  - 'Michael G Schwern <schwern@pobox.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Say-Compat
no_index:
  directory:
    - t
    - inc
requires:
  Perl6::Say: 0.06
resources:
  bugtracker: http://github.com/schwern/say-compat/issues/
  homepage: http://github.com/schwern/say-compat/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/schwern/say-compat/
version: 0.01
